const TURTLES = [
  // ===== 바다거북 (Sea Turtles) =====
  {
    name: "푸른바다거북",
    english: "Green Sea Turtle",
    scientific: "Chelonia mydas",
    family: "바다거북과 (Cheloniidae)",
    habitat: "sea",
    region: "전 세계 열대·온대 해역",
    size: "80~150cm",
    weight: "110~190kg",
    lifespan: "60~80년",
    diet: "해초, 해조류 (성체는 초식)",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Green_sea_turtle_swimming_over_coral_reefs_in_Kona.jpg/640px-Green_sea_turtle_swimming_over_coral_reefs_in_Kona.jpg",
    description: "전 세계 열대 및 아열대 해역에 서식하는 대형 바다거북입니다. 성체는 주로 해초와 해조류를 먹는 초식성으로, 이름은 체지방의 녹색빛에서 유래했습니다. 산란을 위해 수천 km를 이동하며, 태어난 해변으로 돌아오는 놀라운 귀소본능을 가지고 있습니다."
  },
  {
    name: "붉은바다거북",
    english: "Loggerhead Sea Turtle",
    scientific: "Caretta caretta",
    family: "바다거북과 (Cheloniidae)",
    habitat: "sea",
    region: "전 세계 열대·온대 해역",
    size: "70~120cm",
    weight: "80~200kg",
    lifespan: "50~67년",
    diet: "갑각류, 조개, 해파리",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Loggerhead_sea_turtle_%28caretta_caretta%29.jpg/640px-Loggerhead_sea_turtle_%28caretta_caretta%29.jpg",
    description: "큰 머리와 강력한 턱을 가진 바다거북으로, 조개나 갑각류의 껍데기를 부수어 먹습니다. 대서양, 태평양, 인도양의 온대 및 열대 해역에 널리 분포하며, 한국 연안에서도 관찰됩니다."
  },
  {
    name: "장수거북",
    english: "Leatherback Sea Turtle",
    scientific: "Dermochelys coriacea",
    family: "장수거북과 (Dermochelyidae)",
    habitat: "sea",
    region: "전 세계 열대·온대 해역",
    size: "130~180cm",
    weight: "250~700kg",
    lifespan: "45~50년",
    diet: "해파리, 말미잘",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Leatherback_sea_turtle_Tinglar%2C_USVI_%285839996547%29.jpg/640px-Leatherback_sea_turtle_Tinglar%2C_USVI_%285839996547%29.jpg",
    description: "현존하는 가장 큰 거북으로, 길이 2m, 무게 700kg까지 자랍니다. 딱딱한 등딱지 대신 가죽 같은 피부로 덮여 있어 '장수(革)'거북이라 불립니다. 가장 깊이 잠수하는 파충류(1,280m 기록)이며, 찬 바다에서도 체온을 유지할 수 있습니다."
  },
  {
    name: "대모거북",
    english: "Hawksbill Sea Turtle",
    scientific: "Eretmochelys imbricata",
    family: "바다거북과 (Cheloniidae)",
    habitat: "sea",
    region: "전 세계 열대·온대 해역",
    size: "60~100cm",
    weight: "45~80kg",
    lifespan: "30~50년",
    diet: "해면동물, 해파리, 산호",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Hawksbill_Sea_Turtle_Carey_de_Concha_%288407535777%29.jpg/640px-Hawksbill_Sea_Turtle_Carey_de_Concha_%288407535777%29.jpg",
    description: "매의 부리처럼 뾰족한 입을 가진 아름다운 바다거북입니다. 산호초에 서식하며 해면동물을 주로 먹습니다. 아름다운 등딱지 때문에 남획되어 심각한 멸종 위기에 처해 있습니다."
  },
  {
    name: "올리브각시바다거북",
    english: "Olive Ridley Sea Turtle",
    scientific: "Lepidochelys olivacea",
    family: "바다거북과 (Cheloniidae)",
    habitat: "sea",
    region: "전 세계 열대·온대 해역",
    size: "55~75cm",
    weight: "35~50kg",
    lifespan: "50년 이상",
    diet: "새우, 게, 해파리, 조류",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Olive_ridley_sea_turtle.jpg/640px-Olive_ridley_sea_turtle.jpg",
    description: "가장 수가 많은 바다거북 종으로, 올리브색 등딱지가 특징입니다. '아리바다(arribada)'라 불리는 대규모 집단 산란으로 유명하며, 수천 마리가 동시에 해변에 올라와 알을 낳습니다."
  },
  {
    name: "켐프각시바다거북",
    english: "Kemp's Ridley Sea Turtle",
    scientific: "Lepidochelys kempii",
    family: "바다거북과 (Cheloniidae)",
    habitat: "sea",
    region: "북아메리카",
    size: "55~70cm",
    weight: "30~50kg",
    lifespan: "30~50년",
    diet: "게, 새우, 조개, 해파리",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Lepidochelys-kempii.jpg/640px-Lepidochelys-kempii.jpg",
    description: "가장 작고 가장 위험에 처한 바다거북 종입니다. 멕시코 만과 대서양 서부에 서식하며, 멕시코 타마울리파스 해변에서 주로 산란합니다."
  },
  {
    name: "넓적바다거북",
    english: "Flatback Sea Turtle",
    scientific: "Natator depressus",
    family: "바다거북과 (Cheloniidae)",
    habitat: "sea",
    region: "오세아니아",
    size: "76~96cm",
    weight: "70~90kg",
    lifespan: "50년 이상",
    diet: "해삼, 해파리, 새우, 해조류",
    status: "DD",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flatback_sea_turtle.jpg/640px-Flatback_sea_turtle.jpg",
    description: "호주 북부 연안에서만 발견되는 고유종 바다거북입니다. 등딱지가 다른 바다거북에 비해 납작하여 '넓적바다거북'이라 불립니다."
  },

  // ===== 육지거북 (Tortoises) =====
  {
    name: "갈라파고스땅거북",
    english: "Galápagos Giant Tortoise",
    scientific: "Chelonoidis nigra complex",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "남아메리카",
    size: "120~150cm",
    weight: "150~400kg",
    lifespan: "100~175년",
    diet: "선인장, 풀, 과일, 잎",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Geochelone_nigra_abingdonii.jpg/640px-Geochelone_nigra_abingdonii.jpg",
    description: "세계에서 가장 큰 육지거북으로, 갈라파고스 제도의 상징입니다. 찰스 다윈이 진화론의 영감을 얻은 동물이기도 합니다. '외로운 조지(Lonesome George)'로 유명한 핀타섬 아종은 2012년 마지막 개체가 사망했습니다."
  },
  {
    name: "알다브라자이언트거북",
    english: "Aldabra Giant Tortoise",
    scientific: "Aldabrachelys gigantea",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "90~120cm",
    weight: "150~250kg",
    lifespan: "100~200년",
    diet: "풀, 잎, 줄기, 과일",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Aldabra_Giant_Tortoise_Geochelone_gigantea_edit1.jpg/640px-Aldabra_Giant_Tortoise_Geochelone_gigantea_edit1.jpg",
    description: "세이셸 알다브라 환초에 서식하는 대형 육지거북으로, 갈라파고스 거북과 함께 세계 최대 육지거북입니다. 약 10만 마리가 알다브라 환초에 살고 있으며, 200년 이상 사는 것으로 알려져 있습니다."
  },
  {
    name: "아프리카박차거북",
    english: "African Spurred Tortoise (Sulcata)",
    scientific: "Centrochelys sulcata",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "60~83cm",
    weight: "45~100kg",
    lifespan: "70~100년",
    diet: "풀, 건초, 잎, 꽃",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Centrochelys_sulcata_-_Houston_Zoo_-_cropped.jpg/640px-Centrochelys_sulcata_-_Houston_Zoo_-_cropped.jpg",
    description: "아프리카 대륙 최대의 육지거북이자, 세계에서 세 번째로 큰 육지거북입니다. 사하라 사막 남쪽 가장자리의 사헬 지역에 서식합니다. 뒷다리의 큰 박차(돌기)가 특징이며, 더위를 피하기 위해 깊은 굴을 팝니다."
  },
  {
    name: "레오파드거북",
    english: "Leopard Tortoise",
    scientific: "Stigmochelys pardalis",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "40~70cm",
    weight: "13~40kg",
    lifespan: "50~100년",
    diet: "풀, 잡초, 다육식물, 과일",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Leopard_tortoise_-Tanzania.jpg/640px-Leopard_tortoise_-Tanzania.jpg",
    description: "등딱지에 표범 무늬와 유사한 검은 점과 줄무늬가 있어 이름이 붙었습니다. 동아프리카와 남아프리카의 사바나와 초원에 서식하며, 아프리카에서 네 번째로 큰 육지거북입니다."
  },
  {
    name: "헤르만거북",
    english: "Hermann's Tortoise",
    scientific: "Testudo hermanni",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "유럽",
    size: "15~28cm",
    weight: "2~4kg",
    lifespan: "50~75년",
    diet: "풀, 꽃, 잎, 과일",
    status: "NT",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Testudo_hermanni_hermanni_Mallorca_02.jpg/640px-Testudo_hermanni_hermanni_Mallorca_02.jpg",
    description: "남유럽의 지중해 연안에 서식하는 소형~중형 육지거북입니다. 노란색과 검은색의 아름다운 등딱지 무늬가 특징이며, 유럽에서 가장 인기있는 애완 거북 중 하나입니다."
  },
  {
    name: "그리스거북",
    english: "Greek Tortoise (Spur-thighed)",
    scientific: "Testudo graeca",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "유럽",
    size: "13~30cm",
    weight: "1~5kg",
    lifespan: "50~125년",
    diet: "풀, 잎, 꽃, 과일",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Testudo_graeca_ibera.JPG/640px-Testudo_graeca_ibera.JPG",
    description: "남유럽, 북아프리카, 서아시아에 광범위하게 분포하는 육지거북입니다. 뒷다리에 있는 작은 박차가 특징이며, 다양한 아종이 있습니다."
  },
  {
    name: "러시아거북",
    english: "Russian Tortoise (Horsfield's)",
    scientific: "Testudo horsfieldii",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아시아",
    size: "13~25cm",
    weight: "0.5~2.5kg",
    lifespan: "40~50년",
    diet: "풀, 잎, 꽃, 과일",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Testudo_horsfieldii.jpg/640px-Testudo_horsfieldii.jpg",
    description: "중앙아시아의 건조한 초원과 사막에 서식하는 소형 육지거북입니다. 러시아, 우즈베키스탄, 이란, 아프가니스탄, 파키스탄에 분포합니다. 추위에 강하고 크기가 작아 애완용으로 인기가 높습니다."
  },
  {
    name: "인도별거북",
    english: "Indian Star Tortoise",
    scientific: "Geochelone elegans",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아시아",
    size: "20~38cm",
    weight: "1.5~7kg",
    lifespan: "35~80년",
    diet: "풀, 꽃, 과일, 잎",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/IndianStarTortoise.jpg/640px-IndianStarTortoise.jpg",
    description: "등딱지에 별 모양의 아름다운 방사형 무늬가 있는 인도, 스리랑카, 파키스탄의 육지거북입니다. 높이 솟은 돔형 등딱지가 특징이며, 아름다운 외모 때문에 불법 밀거래의 대상이 되고 있습니다."
  },
  {
    name: "방사거북",
    english: "Radiated Tortoise",
    scientific: "Astrochelys radiata",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "30~40cm",
    weight: "10~16kg",
    lifespan: "40~100년 이상",
    diet: "풀, 과일, 선인장",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Radiated_tortoise_%28Astrochelys_radiata%29_3.jpg/640px-Radiated_tortoise_%28Astrochelys_radiata%29_3.jpg",
    description: "마다가스카르 남부에만 서식하는 아름다운 육지거북으로, 등딱지의 노란색 방사형 무늬가 매우 화려합니다. 세계에서 가장 아름다운 거북 중 하나로 꼽힙니다."
  },
  {
    name: "팬케이크거북",
    english: "Pancake Tortoise",
    scientific: "Malacochersus tornieri",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "15~18cm",
    weight: "0.4~0.6kg",
    lifespan: "25~35년",
    diet: "풀, 마른 잎, 다육식물",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Malacochersus_tornieri_-_National_Museum_of_Nature_and_Science%2C_Tokyo_-_DSC06686.JPG/640px-Malacochersus_tornieri_-_National_Museum_of_Nature_and_Science%2C_Tokyo_-_DSC06686.JPG",
    description: "이름처럼 납작한 등딱지를 가진 독특한 거북으로, 동아프리카의 바위 틈에 살며 위험할 때 바위 사이로 몸을 부풀려 끼워 넣습니다. 다른 육지거북과 달리 빠르고 민첩합니다."
  },
  {
    name: "붉은발거북",
    english: "Red-footed Tortoise",
    scientific: "Chelonoidis carbonarius",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "남아메리카",
    size: "25~45cm",
    weight: "4~15kg",
    lifespan: "50년 이상",
    diet: "과일, 꽃, 잎, 버섯, 무척추동물",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Chelonoidis_carbonaria_-_Red-Footed_Tortoise_01.jpg/640px-Chelonoidis_carbonaria_-_Red-Footed_Tortoise_01.jpg",
    description: "남아메리카 열대 지역에 서식하며, 다리와 머리에 빨간색 또는 주황색 비늘이 특징적입니다. 잡식성으로 과일, 꽃, 버섯 등을 먹습니다."
  },
  {
    name: "노란발거북",
    english: "Yellow-footed Tortoise",
    scientific: "Chelonoidis denticulatus",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "남아메리카",
    size: "40~75cm",
    weight: "15~30kg",
    lifespan: "50~60년",
    diet: "과일, 잎, 꽃, 버섯",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Chelonoidis_denticulata_-_Yellow-Footed_Tortoise_02.jpg/640px-Chelonoidis_denticulata_-_Yellow-Footed_Tortoise_02.jpg",
    description: "남아메리카의 아마존 열대우림에 서식하는 대형 육지거북으로, 대륙 최대의 육지거북입니다. 다리에 노란색 비늘이 있습니다."
  },
  {
    name: "앙고노카거북",
    english: "Ploughshare Tortoise (Angonoka)",
    scientific: "Astrochelys yniphora",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "35~45cm",
    weight: "8~12kg",
    lifespan: "50~100년",
    diet: "풀, 관목, 잎",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Angonoka_%28Astrochelys_yniphora%29.jpg/640px-Angonoka_%28Astrochelys_yniphora%29.jpg",
    description: "마다가스카르 북서부에만 서식하는 세계에서 가장 희귀한 거북 중 하나입니다. 수컷의 목 아래 돌출된 쟁기(ploughshare) 모양의 등딱지판이 특징적입니다. 야생에서 약 400마리만 남아있습니다."
  },
  {
    name: "이집트거북",
    english: "Egyptian Tortoise",
    scientific: "Testudo kleinmanni",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "8~14cm",
    weight: "0.1~0.4kg",
    lifespan: "30~50년",
    diet: "풀, 잎, 꽃",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Testudo_kleinmanni.jpg/640px-Testudo_kleinmanni.jpg",
    description: "북아프리카(이집트, 리비아)에 서식하는 매우 작은 육지거북으로, 북반구에서 가장 작은 거북입니다. 연한 황금색 등딱지가 아름다우며, 서식지 파괴로 이집트에서는 거의 멸종했습니다."
  },
  {
    name: "마르기나타거북",
    english: "Marginated Tortoise",
    scientific: "Testudo marginata",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "유럽",
    size: "25~35cm",
    weight: "3~5kg",
    lifespan: "50~100년",
    diet: "풀, 잎, 꽃, 과일",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Testudo_marginata_5.jpg/640px-Testudo_marginata_5.jpg",
    description: "유럽에서 가장 큰 육지거북으로, 그리스와 이탈리아 남부에 서식합니다. 등딱지 뒤쪽이 치마처럼 넓게 퍼지는 독특한 형태가 특징입니다."
  },
  {
    name: "비르마별거북",
    english: "Burmese Star Tortoise",
    scientific: "Geochelone platynota",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아시아",
    size: "22~30cm",
    weight: "2~5kg",
    lifespan: "40~80년",
    diet: "풀, 과일, 버섯",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Geochelone_platynota.jpg/640px-Geochelone_platynota.jpg",
    description: "미얀마에만 서식하는 고유종으로, 인도별거북과 비슷하지만 별 무늬가 더 선명합니다. 야생에서 거의 멸종 상태였으나, 보전 프로그램으로 개체수가 회복되고 있습니다."
  },
  {
    name: "거미거북",
    english: "Spider Tortoise",
    scientific: "Pyxis arachnoides",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "12~15cm",
    weight: "0.2~0.4kg",
    lifespan: "40~70년",
    diet: "식물, 곤충, 과일",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Pyxis_arachnoides_-_Madagascar.jpg/640px-Pyxis_arachnoides_-_Madagascar.jpg",
    description: "마다가스카르 남서부에만 서식하는 소형 거북으로, 등딱지의 노란 방사형 무늬가 거미줄과 닮아 이름이 붙었습니다."
  },

  // ===== 민물거북 (Freshwater Turtles) =====
  {
    name: "붉은귀거북 (슬라이더)",
    english: "Red-eared Slider",
    scientific: "Trachemys scripta elegans",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "15~33cm",
    weight: "1~3kg",
    lifespan: "20~40년",
    diet: "수생식물, 곤충, 물고기, 갑각류",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Trachemys_scripta_elegans_-_Red-eared_Slider.jpg/640px-Trachemys_scripta_elegans_-_Red-eared_Slider.jpg",
    description: "귀 부분의 빨간 줄무늬가 특징인 북아메리카 원산의 민물거북입니다. 전 세계적으로 가장 인기있는 애완 거북이지만, 방류로 인해 최악의 침입종 100종에 포함되어 있습니다."
  },
  {
    name: "남생이",
    english: "Chinese Stripe-necked Turtle",
    scientific: "Mauremys sinensis",
    family: "돌거북과 (Geoemydidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "20~30cm",
    weight: "1~3kg",
    lifespan: "25~40년",
    diet: "수생식물, 물고기, 곤충",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Mauremys_sinensis_2008.jpg/640px-Mauremys_sinensis_2008.jpg",
    description: "한국, 중국, 대만, 베트남에 서식하는 민물거북으로, 한국의 대표적인 토종 거북입니다. 목에 노란색 줄무늬가 있으며, 천연기념물 제453호로 지정되어 보호받고 있습니다."
  },
  {
    name: "자라",
    english: "Chinese Softshell Turtle",
    scientific: "Pelodiscus sinensis",
    family: "자라과 (Trionychidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "20~33cm",
    weight: "1~4.5kg",
    lifespan: "20~30년",
    diet: "물고기, 새우, 곤충, 조개",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Pelodiscus_sinensis_2008.jpg/640px-Pelodiscus_sinensis_2008.jpg",
    description: "딱딱한 등딱지 대신 부드러운 가죽 같은 껍질을 가진 민물거북입니다. 동아시아에 널리 분포하며, 물속에서 피부 호흡을 할 수 있습니다."
  },
  {
    name: "악어거북",
    english: "Alligator Snapping Turtle",
    scientific: "Macrochelys temminckii",
    family: "악어거북과 (Chelydridae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "40~80cm",
    weight: "30~100kg (최대 183kg)",
    lifespan: "50~100년",
    diet: "물고기, 뱀, 거북, 수생식물",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Alligator_snapping_turtle.jpg/640px-Alligator_snapping_turtle.jpg",
    description: "북아메리카 최대의 민물거북으로, 공룡 시대를 연상시키는 외모를 가지고 있습니다. 혀에 있는 벌레 모양의 돌기로 물고기를 유인하는 독특한 사냥법을 사용합니다."
  },
  {
    name: "늑대거북",
    english: "Common Snapping Turtle",
    scientific: "Chelydra serpentina",
    family: "악어거북과 (Chelydridae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "25~47cm",
    weight: "4.5~16kg",
    lifespan: "30~50년",
    diet: "물고기, 개구리, 뱀, 새, 수생식물",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Common_Snapping_Turtle_Close_Up.jpg/640px-Common_Snapping_Turtle_Close_Up.jpg",
    description: "북아메리카에 광범위하게 분포하는 대형 민물거북으로, 공격적인 성격과 강한 턱으로 유명합니다."
  },
  {
    name: "마타마타",
    english: "Mata Mata",
    scientific: "Chelus fimbriata",
    family: "뱀목거북과 (Chelidae)",
    habitat: "freshwater",
    region: "남아메리카",
    size: "35~55cm",
    weight: "10~15kg",
    lifespan: "40~75년",
    diet: "물고기",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Chelus_fimbriatus_2005.jpg/640px-Chelus_fimbriatus_2005.jpg",
    description: "남아메리카 아마존과 오리노코 강 유역에 서식하는 독특한 외모의 민물거북입니다. 납작한 삼각형 머리, 긴 코, 울퉁불퉁한 등딱지로 낙엽처럼 위장합니다."
  },
  {
    name: "돼지코거북",
    english: "Pig-nosed Turtle",
    scientific: "Carettochelys insculpta",
    family: "돼지코거북과 (Carettochelyidae)",
    habitat: "freshwater",
    region: "오세아니아",
    size: "46~56cm",
    weight: "15~25kg",
    lifespan: "25~50년",
    diet: "과일, 잎, 조류, 갑각류, 곤충",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Carettochelys_insculpta.jpg/640px-Carettochelys_insculpta.jpg",
    description: "호주 북부와 뉴기니에 서식하는 독특한 민물거북으로, 바다거북처럼 지느러미 형태의 앞다리를 가진 유일한 민물거북입니다."
  },
  {
    name: "다이아몬드등거북",
    english: "Diamondback Terrapin",
    scientific: "Malaclemys terrapin",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "10~23cm",
    weight: "0.2~1kg",
    lifespan: "25~40년",
    diet: "달팽이, 갑각류, 조개, 물고기",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Malaclemys_terrapin_-_Diamondback_Terrapin.jpg/640px-Malaclemys_terrapin_-_Diamondback_Terrapin.jpg",
    description: "미국 동부와 남부의 기수 습지에 서식하는 유일한 거북으로, 등딱지에 다이아몬드 모양의 무늬가 있습니다."
  },
  {
    name: "페인티드거북",
    english: "Painted Turtle",
    scientific: "Chrysemys picta",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "10~25cm",
    weight: "0.2~0.6kg",
    lifespan: "25~50년",
    diet: "수생식물, 곤충, 갑각류, 물고기",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Painted_Turtle.jpg/640px-Painted_Turtle.jpg",
    description: "북아메리카에서 가장 널리 분포하는 거북으로, 등딱지 가장자리와 피부에 빨간색, 노란색의 선명한 줄무늬가 특징입니다."
  },
  {
    name: "상자거북",
    english: "Eastern Box Turtle",
    scientific: "Terrapene carolina",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "12~20cm",
    weight: "0.4~0.8kg",
    lifespan: "50~100년",
    diet: "곤충, 지렁이, 버섯, 열매, 잎",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Terrapene_carolina_carolina_-_Puddle_%288743950534%29.jpg/640px-Terrapene_carolina_carolina_-_Puddle_%288743950534%29.jpg",
    description: "미국 동부의 숲에 사는 반수생 거북으로, 등딱지를 완전히 닫아 상자처럼 만들 수 있는 경첩 구조의 배딱지가 특징입니다."
  },
  {
    name: "나무거북",
    english: "Wood Turtle",
    scientific: "Glyptemys insculpta",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "14~23cm",
    weight: "0.5~1kg",
    lifespan: "40~60년",
    diet: "식물, 곤충, 지렁이, 버섯, 열매",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Glyptemys_insculpta.jpg/640px-Glyptemys_insculpta.jpg",
    description: "북아메리카 북동부의 숲과 하천에 서식하며, 거북 중 가장 지능이 높은 것으로 알려져 있습니다."
  },
  {
    name: "머레이강거북",
    english: "Murray River Short-necked Turtle",
    scientific: "Emydura macquarii",
    family: "뱀목거북과 (Chelidae)",
    habitat: "freshwater",
    region: "오세아니아",
    size: "20~30cm",
    weight: "1~3kg",
    lifespan: "30~40년",
    diet: "수생식물, 갑각류, 곤충",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Emydura_macquarii_krefftii.jpg/640px-Emydura_macquarii_krefftii.jpg",
    description: "호주 남동부 머레이강 유역에 서식하는 민물거북으로, 짧은 목이 특징입니다. 호주에서 가장 흔한 거북 중 하나입니다."
  },
  {
    name: "긴목거북",
    english: "Eastern Long-necked Turtle",
    scientific: "Chelodina longicollis",
    family: "뱀목거북과 (Chelidae)",
    habitat: "freshwater",
    region: "오세아니아",
    size: "20~28cm",
    weight: "0.5~1.5kg",
    lifespan: "30~50년",
    diet: "물고기, 갑각류, 올챙이, 곤충",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Eastern_long-neck_turtle.jpg/640px-Eastern_long-neck_turtle.jpg",
    description: "호주 동부에 서식하며, 등딱지 길이만큼 긴 목이 특징입니다. 뱀처럼 긴 목을 옆으로 접어 등딱지 안에 넣습니다."
  },
  {
    name: "양쯔강자라",
    english: "Yangtze Giant Softshell Turtle",
    scientific: "Rafetus swinhoei",
    family: "자라과 (Trionychidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "80~100cm",
    weight: "80~120kg",
    lifespan: "100년 이상",
    diet: "물고기, 게, 달팽이, 수생식물",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Rafetus_swinhoei_-_Shanghai_Zoo.jpg/640px-Rafetus_swinhoei_-_Shanghai_Zoo.jpg",
    description: "세계에서 가장 희귀한 거북으로, 현재 확인된 개체가 2~3마리에 불과합니다. 기능적 멸종 상태에 가깝습니다."
  },
  {
    name: "지도거북",
    english: "Common Map Turtle",
    scientific: "Graptemys geographica",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "10~27cm",
    weight: "0.2~2.5kg",
    lifespan: "15~20년",
    diet: "갑각류, 연체동물, 곤충",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Graptemys_geographica.jpg/640px-Graptemys_geographica.jpg",
    description: "등딱지의 무늬가 지도의 등고선과 닮아 이름이 붙은 북아메리카 민물거북입니다."
  },
  {
    name: "머스크거북",
    english: "Common Musk Turtle (Stinkpot)",
    scientific: "Sternotherus odoratus",
    family: "진흙거북과 (Kinosternidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "5~14cm",
    weight: "0.05~0.3kg",
    lifespan: "30~50년",
    diet: "곤충, 연체동물, 수생식물",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Sternotherus_odoratus.jpg/640px-Sternotherus_odoratus.jpg",
    description: "북아메리카에서 가장 작은 거북 중 하나로, 위협을 느끼면 사향샘에서 강한 악취를 내뿜어 'Stinkpot'이라는 별명이 있습니다."
  },
  {
    name: "진흙거북",
    english: "Eastern Mud Turtle",
    scientific: "Kinosternon subrubrum",
    family: "진흙거북과 (Kinosternidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "7~12cm",
    weight: "0.1~0.3kg",
    lifespan: "30~50년",
    diet: "곤충, 새우, 달팽이, 수생식물",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Kinosternon_subrubrum.jpg/640px-Kinosternon_subrubrum.jpg",
    description: "미국 동부의 얕은 연못, 습지, 늪에 서식하는 소형 민물거북입니다. 배딱지에 경첩이 있어 부분적으로 닫을 수 있습니다."
  },
  {
    name: "부채머리거북",
    english: "Big-headed Turtle",
    scientific: "Platysternon megacephalum",
    family: "부채머리거북과 (Platysternidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "15~20cm",
    weight: "0.3~0.5kg",
    lifespan: "20~30년",
    diet: "물고기, 갑각류, 곤충",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Platysternon_megacephalum.jpg/640px-Platysternon_megacephalum.jpg",
    description: "동남아시아의 산간 계류에 서식하며, 몸에 비해 매우 큰 머리가 특징입니다. 나무를 타는 능력이 있는 독특한 거북입니다."
  },
  {
    name: "인도지붕거북",
    english: "Indian Roofed Turtle",
    scientific: "Pangshura tecta",
    family: "돌거북과 (Geoemydidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "15~23cm",
    weight: "0.5~2kg",
    lifespan: "15~25년",
    diet: "수생식물, 과일, 꽃",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Pangshura_tecta.jpg/640px-Pangshura_tecta.jpg",
    description: "인도, 파키스탄, 방글라데시, 네팔의 큰 강에 서식하며, 등딱지 중앙에 솟은 돌기가 지붕처럼 보여 이름이 붙었습니다."
  },
  {
    name: "메콩강자라",
    english: "Cantor's Giant Softshell Turtle",
    scientific: "Pelochelys cantorii",
    family: "자라과 (Trionychidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "100~200cm",
    weight: "50~100kg 이상",
    lifespan: "50년 이상",
    diet: "물고기, 갑각류, 연체동물",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Pelochelys_cantorii.jpg/640px-Pelochelys_cantorii.jpg",
    description: "동남아시아 최대의 민물거북 중 하나로, 길이가 2m에 달할 수 있습니다. 하루의 95%를 모래나 진흙에 묻혀 보냅니다."
  },
  {
    name: "플로리다자라",
    english: "Florida Softshell Turtle",
    scientific: "Apalone ferox",
    family: "자라과 (Trionychidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "15~65cm",
    weight: "2~20kg",
    lifespan: "20~30년",
    diet: "물고기, 갑각류, 달팽이, 곤충",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Florida_softshell_turtle.jpg/640px-Florida_softshell_turtle.jpg",
    description: "미국 플로리다를 중심으로 남동부에 서식하는 대형 자라입니다. 북아메리카에서 가장 큰 자라 종입니다."
  },
  {
    name: "유럽연못거북",
    english: "European Pond Turtle",
    scientific: "Emys orbicularis",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "유럽",
    size: "12~23cm",
    weight: "0.4~1.5kg",
    lifespan: "40~100년",
    diet: "곤충, 갑각류, 물고기, 수생식물",
    status: "NT",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Emys_orbicularis.jpg/640px-Emys_orbicularis.jpg",
    description: "유럽에서 가장 널리 분포하는 민물거북으로, 검은 등딱지에 노란색 점이 있습니다."
  },
  {
    name: "바타구르강거북",
    english: "Batagur (Northern River Terrapin)",
    scientific: "Batagur baska",
    family: "돌거북과 (Geoemydidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "40~60cm",
    weight: "15~25kg",
    lifespan: "50년 이상",
    diet: "수생식물, 맹그로브 열매",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Batagur_baska_001.jpg/640px-Batagur_baska_001.jpg",
    description: "인도, 방글라데시, 미얀마의 큰 강과 기수역에 서식하던 대형 민물거북입니다. 번식기에 수컷의 머리가 선명한 빨간색과 검은색으로 변합니다."
  },
  {
    name: "머드거북 (중앙아메리카)",
    english: "Scorpion Mud Turtle",
    scientific: "Kinosternon scorpioides",
    family: "진흙거북과 (Kinosternidae)",
    habitat: "freshwater",
    region: "남아메리카",
    size: "15~27cm",
    weight: "0.3~0.6kg",
    lifespan: "20~30년",
    diet: "곤충, 식물, 작은 동물",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Kinosternon_scorpioides.jpg/640px-Kinosternon_scorpioides.jpg",
    description: "중앙아메리카와 남아메리카 북부에 분포하는 진흙거북으로, 꼬리 끝에 전갈의 침처럼 생긴 돌기가 있어 이름이 붙었습니다."
  },
  {
    name: "사향거북 (로게로)",
    english: "Loggerhead Musk Turtle",
    scientific: "Sternotherus minor",
    family: "진흙거북과 (Kinosternidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "7~14cm",
    weight: "0.1~0.4kg",
    lifespan: "20~30년",
    diet: "달팽이, 조개, 곤충",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Sternotherus_minor.jpg/640px-Sternotherus_minor.jpg",
    description: "미국 남동부의 맑은 하천과 샘에 서식하는 소형 민물거북입니다. 몸에 비해 큰 머리와 강한 턱이 특징입니다."
  },
  {
    name: "쿠터거북",
    english: "River Cooter",
    scientific: "Pseudemys concinna",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "23~40cm",
    weight: "2~5kg",
    lifespan: "20~40년",
    diet: "수생식물 (초식)",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Pseudemys_concinna_concinna.jpg/640px-Pseudemys_concinna_concinna.jpg",
    description: "미국 동부의 강과 호수에 서식하는 대형 민물거북입니다. 주로 초식성으로 수생식물을 먹습니다."
  },
  {
    name: "블랜딩거북",
    english: "Blanding's Turtle",
    scientific: "Emydoidea blandingii",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "15~27cm",
    weight: "0.7~1.5kg",
    lifespan: "50~80년",
    diet: "갑각류, 곤충, 물고기, 식물",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Emydoidea_blandingii.jpg/640px-Emydoidea_blandingii.jpg",
    description: "미국 북동부와 오대호 지역에 서식하며, 밝은 노란색 턱과 목이 특징입니다."
  },
  {
    name: "가시자라",
    english: "Spiny Softshell Turtle",
    scientific: "Apalone spinifera",
    family: "자라과 (Trionychidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "12~54cm",
    weight: "1~12kg",
    lifespan: "20~50년",
    diet: "곤충, 가재, 물고기",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Apalone_spinifera.jpg/640px-Apalone_spinifera.jpg",
    description: "북아메리카에 널리 분포하는 자라로, 등딱지 앞쪽 가장자리에 작은 가시 같은 돌기가 있어 이름이 붙었습니다."
  },
  {
    name: "로티거북 (로티뱀목거북)",
    english: "Roti Island Snake-necked Turtle",
    scientific: "Chelodina mccordi",
    family: "뱀목거북과 (Chelidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "15~24cm",
    weight: "0.5~1kg",
    lifespan: "30~50년",
    diet: "물고기, 갑각류, 곤충",
    status: "CR",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Chelodina_mccordi.jpg/640px-Chelodina_mccordi.jpg",
    description: "인도네시아 로티섬에만 서식하는 극소형 뱀목거북으로, 세계에서 가장 희귀한 거북 중 하나입니다."
  },

  // ===== 추가 종 =====
  {
    name: "사막거북",
    english: "Desert Tortoise",
    scientific: "Gopherus agassizii",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "북아메리카",
    size: "25~37cm",
    weight: "4~7kg",
    lifespan: "50~80년",
    diet: "풀, 꽃, 선인장 열매",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Gopherus_agassizii.jpg/640px-Gopherus_agassizii.jpg",
    description: "미국 남서부의 모하비 사막과 소노란 사막에 서식합니다. 일생의 95%를 지하 굴에서 보내며, 방광에 물을 저장할 수 있습니다."
  },
  {
    name: "고퍼거북",
    english: "Gopher Tortoise",
    scientific: "Gopherus polyphemus",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "북아메리카",
    size: "23~38cm",
    weight: "4~6kg",
    lifespan: "40~80년",
    diet: "풀, 잎, 과일, 꽃",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Gopher_tortoise_%28Gopherus_polyphemus%29.jpg/640px-Gopher_tortoise_%28Gopherus_polyphemus%29.jpg",
    description: "미국 남동부에 서식하며, 깊은 굴을 파는 능력으로 유명합니다. 굴은 350종 이상의 다른 동물에게 피난처를 제공하여 '핵심종'으로 불립니다."
  },
  {
    name: "쟁기등거북",
    english: "Home's Hinge-back Tortoise",
    scientific: "Kinixys homeana",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "15~22cm",
    weight: "0.5~1.5kg",
    lifespan: "30~50년",
    diet: "곤충, 달팽이, 과일, 버섯",
    status: "VU",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Kinixys_homeana.jpg/640px-Kinixys_homeana.jpg",
    description: "서아프리카와 중앙아프리카의 열대우림에 서식하며, 등딱지 뒤쪽에 경첩이 있어 뒤로 접을 수 있는 독특한 구조를 가지고 있습니다."
  },
  {
    name: "볼슨거북",
    english: "Bolson Tortoise",
    scientific: "Gopherus flavomarginatus",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "북아메리카",
    size: "30~40cm",
    weight: "8~12kg",
    lifespan: "50~100년",
    diet: "풀, 잎, 꽃",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Gopherus_flavomarginatus.jpg/640px-Gopherus_flavomarginatus.jpg",
    description: "멕시코 북부 치와와 사막의 볼손 분지에만 서식하는 희귀한 육지거북입니다. 북아메리카에서 가장 큰 육지거북입니다."
  },
  {
    name: "종거북 (벨거북)",
    english: "Bell's Hinge-back Tortoise",
    scientific: "Kinixys belliana",
    family: "땅거북과 (Testudinidae)",
    habitat: "land",
    region: "아프리카",
    size: "15~22cm",
    weight: "0.7~2kg",
    lifespan: "20~30년",
    diet: "버섯, 과일, 곤충, 달팽이",
    status: "NT",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Kinixys_belliana_nogueyi.jpg/640px-Kinixys_belliana_nogueyi.jpg",
    description: "사하라 이남 아프리카에 널리 분포하는 경첩등거북으로, 사바나와 초원 지대에 서식합니다."
  },
  {
    name: "점박이거북",
    english: "Spotted Turtle",
    scientific: "Clemmys guttata",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "8~13cm",
    weight: "0.1~0.3kg",
    lifespan: "25~50년",
    diet: "곤충, 수생식물, 조류",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Spotted_turtle.jpg/640px-Spotted_turtle.jpg",
    description: "검은 등딱지에 밝은 노란색 점이 박힌 아름다운 소형 거북으로, 미국 동부와 캐나다 남부의 습지에 서식합니다."
  },
  {
    name: "인도덮개거북",
    english: "Indian Flapshell Turtle",
    scientific: "Lissemys punctata",
    family: "자라과 (Trionychidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "22~37cm",
    weight: "2~7kg",
    lifespan: "15~30년",
    diet: "물고기, 개구리, 식물, 곤충",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Lissemys_punctata_-_Karunagappally.jpg/640px-Lissemys_punctata_-_Karunagappally.jpg",
    description: "인도 아대륙에 널리 분포하는 민물거북으로, 배딱지에 달린 가죽 덮개(flap)로 다리를 보호하는 독특한 구조를 가지고 있습니다."
  },
  {
    name: "쿠바슬라이더",
    english: "Cuban Slider",
    scientific: "Trachemys decussata",
    family: "늪거북과 (Emydidae)",
    habitat: "freshwater",
    region: "북아메리카",
    size: "15~39cm",
    weight: "1~5kg",
    lifespan: "20~40년",
    diet: "수생식물, 곤충, 물고기",
    status: "LC",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Trachemys_decussata.jpg/640px-Trachemys_decussata.jpg",
    description: "쿠바와 바하마에 서식하는 민물거북으로, 카리브해 지역의 대표적인 민물 수생거북입니다."
  },
  {
    name: "블랙연못거북",
    english: "Black Pond Turtle",
    scientific: "Geoclemys hamiltonii",
    family: "돌거북과 (Geoemydidae)",
    habitat: "freshwater",
    region: "아시아",
    size: "25~40cm",
    weight: "2~5kg",
    lifespan: "20~30년",
    diet: "달팽이, 수생식물, 과일",
    status: "EN",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Geoclemys_hamiltonii.jpg/640px-Geoclemys_hamiltonii.jpg",
    description: "인도, 파키스탄, 스리랑카, 네팔, 방글라데시의 습지에 서식합니다. 검은 등딱지에 크림색의 점과 줄무늬가 있어 매우 아름다운 종입니다."
  }
];
